#! /bin/sh
#
#
#@# Colors

#----------------------------- Verde
g="\033[1;32m"
#----------------------------- Rojo
r="\033[1;31m"
#----------------------------- Blanco
w="\033[1;37m"
#----------------------------- Azul
b="\033[34m"
#----------------------------- Cyan
c="\033[1;36m"
#----------------------------- Morado
m="\033[35m"
#----------------------------- Amarillo
y="\033[33m"
#----------------------------- Naranja
o="\033[38;5;214m"
#----------------------------- Azul Claro
bb="\033[38;5;39m"
#----------------------------- Rosado
p="\033[38;5;213m"


###



clear
echo "$bb This script prepares the repository so that the .deb is accessible to apt $g 
###############PLEASE WAIT################"

cd $PREFIX/etc/apt/sources.list.d/
cat > cliet.list < EOF
deb [trusted=yes] https://raw.githubusercontent.com/bapm394/termux-adb-dot-deb/master/ termux adb
EOF
cd
